export const GET_PROVIDE_REQUEST = "GET_PROVIDE_REQUEST";
export const GET_PROVIDE_SUCCESS = "GET_PROVIDE_SUCCESS";
export const GET_PROVIDE_FAIL = "GET_PROVIDE_FAIL";

export const GET_DISTRICT_REQUEST = "GET_DISTRICT_REQUEST";
export const GET_DISTRICT_SUCCESS = "GET_DISTRICT_SUCCESS";
export const GET_DISTRICT_FAIL = "GET_DISTRICT_FAIL";

export const GET_WARD_REQUEST = "GET_WARD_REQUEST";
export const GET_WARD_SUCCESS = "GET_WARD_SUCCESS";
export const GET_WARD_FAIL = "GET_WARD_FAIL";